# This is the recipe that tells GitHub's computers how to build your app.
name: Build Al-Madina POS Android App

# This makes the recipe run automatically every time you make a change to your code.
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # The build will run on a standard, powerful Linux server.
    runs-on: ubuntu-latest

    steps:
    # Step 1: It checks out a copy of your repository's code.
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: It sets up the correct Java version (JDK 17) that your app needs.
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Step 3: It makes a special file executable, which is required on Linux.
    - name: Grant execute permission to gradlew
      run: chmod +x android-app/gradlew
      
    # Step 4: This is the main command. It tells Gradle to build the debug APK.
    - name: Build with Gradle
      run: ./android-app/gradlew -p android-app/ assembleDebug

    # Step 5: It takes the finished APK and uploads it so you can download it.
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: al-madina-pos-debug-apk
        path: android-app/app/build/outputs/apk/debug/app-debug.apk
