name: Build Al-Madina POS Android App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x android-app/gradlew

      # --- THE FINAL FIX IS IN THIS STEP ---
      - name: Build with Gradle
        # This command now first changes the directory (cd) into android-app,
        # and then runs the build from inside that folder.
        run: cd android-app && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: al-madina-pos-debug-apk
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
