name: Build Al-Madina POS Android App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checks out the whole repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Sets up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # --- THE KEY FIX ---
    # Step 3: Sets up Gradle by explicitly pointing to the android-app build root
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-root-path: 'android-app' 

    # Step 4: Grant execute permission using the full path
    - name: Grant execute permission to gradlew
      run: chmod +x android-app/gradlew
      
    # Step 5: Build the app using the full path
    - name: Build with Gradle
      run: ./android-app/gradlew -p android-app/ assembleDebug

    # Step 6: Upload the APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: al-madina-pos-debug-apk
        path: android-app/app/build/outputs/apk/debug/app-debug.apk
