name: Build Al-Madina POS Android App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # --- THE KEY FIX ---
    # This tells all steps in this job to run inside the 'android-app' folder
    defaults:
      run:
        working-directory: ./android-app

    steps:
    # Step 1: Checks out the whole repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Sets up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Sets up Gradle correctly inside the android-app directory
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    # Step 4: Grant execute permission. Note the path is simpler now.
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      
    # Step 5: Build the app. Note the path is simpler now.
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    # Step 6: Upload the APK. The path is slightly different here.
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: al-madina-pos-debug-apk
        path: android-app/app/build/outputs/apk/debug/app-debug.apk
